name: Bump version

on:
  workflow_call:
    inputs:
      versionName:
        description: 'Version Name'
        type: string
        required: false
        default: ''
      appStage:
        description: 'App Stage'
        type: string
        required: false
        default: ''
        
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: version extraction
       id: versionReader
       uses: Devofure/version-reader-action@main
       with:
         gradlePath: app/build.gradle
       
     - run: echo  ${{ github.output.versionReader.versionName }}
     - run: echo  ${{ github.output.versionReader.versionCode }}
     - run: echo  ${{ github.output.versionReader.majorVersion }}
     - run: echo  ${{ github.output.versionReader.minorVersion }}
     - run: echo  ${{ github.output.versionReader.patchVersion }}

     - run: echo  ${{ github.output.versionReader.prereleaseVersion }}
     - run: echo  ${{ github.output.versionReader.prereleaseStage }}
     - run: echo  ${{ github.output.versionReader.prereleaseBuildNumber }}
     - run: echo  ${{ github.output.versionReader.buildMetaDataVersion }}
     - run: echo  ${{ github.output.versionReader.buildMetaDataBuildNumber }}
     
     - run: echo  ${{ github.inputs.stage }}

     - uses: actions/checkout@v2

     - name: set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8

     - name: Bump version to Alpha
       id: alphaBump
       uses: Devofure/android-version-actions@master
       if: ${{ github.event.inputs.stage == 'alpha' }}
       with:
         gradlePath: app/build.gradle
         versionName: ${{ github.inputs.versionName }}
         versionStage: a
          
     - name: Bump version to Beta
       uses: Devofure/android-version-actions@master
       if: ${{ github.inputs.stage != 'alpha' && github.inputs.stage != 'release' }}
       with:
         gradlePath: app/build.gradle
         versionName: ${{ github.inputs.versionName }}
         versionStage: b
         versionCodeLimiter: 3

     - name: Bump version to Release
       uses: Devofure/android-version-actions@master
       if: ${{ github.inputs.stage == 'release' }}
       with:
         gradlePath: app/build.gradle
         versionName: ${{ github.inputs.versionName }}
         versionStage: ''
     - run: echo ${{ github.output.alphaBump.versionName }}
