name: Android CI

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: false
        default: ''
      stage:
        type: choice
        description: 'The stage of the app: b = beta empty = release'
        options: 
        - beta
        - alpha
        - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Bump version to Alpha
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'alpha' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: a
          
      - name: Bump version to Beta
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'beta' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: b

      - name: Bump version to Release
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'release' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: ' '

      - uses: EndBug/add-and-commit@v8
        with:
          add: app/build.gradle
          message: 'Version code increased'
          default_author: github_actions
