name: Android CI

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: false
        default: ''
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: Devofure/android-version-actions@master
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          
      - uses: EndBug/add-and-commit@v8
        with:
          add: app/build.gradle
          message: 'Version code increased'
          default_author: github_actions
