name: Bump version and tag

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: false
        default: ''
      stage:
        type: choice
        description: 'The stage of the app: b = beta empty = release'
        options: 
        - beta
        - alpha
        - release
      variantName:
        type: choice
        description: 'App vairant'
        options: 
        - app1
        - app2
        - app3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Bump version to Alpha
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'alpha' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: a
          
      - name: Bump version to Beta
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage != 'alpha' && github.event.inputs.stage != 'release' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: b
          versionCodeLimiter: 3

      - name: Bump version to Release
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'release' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: ' '

      - uses: younited/get-previous-tag-action@v1.0.0
        id: variant_type
        with:
          prefix: ${{ github.event.inputs.variantName }}
      
      - run: echo  ${{ steps.variant_type.outputs.previous-tag }}

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          fromTag: "0.0.1"
          toTag: ${{ steps.variant_type.outputs.previous-tag }}
          
      - run: echo  ${{ steps.build_changelog.outputs.changelog }}
      
      - uses: EndBug/add-and-commit@v8
        with:
          add: app/build.gradle
          message: ${{steps.build_changelog.outputs.changelog}}
          default_author: github_actions
      
