name: change stage and auto increse version code
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Name'
        required: false
        default: ''
      stage:
        type: choice
        description: 'The stage of the app'
        options: 
        - beta
        - alpha
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Bump version to Alpha
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'alpha' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: a
          versionCodeLimiter: 3

      - name: Bump version to Beta
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage != 'alpha' && github.event.inputs.stage != 'release' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: b
          versionCodeLimiter: 3

      - name: Bump version to Release
        uses: Devofure/android-version-actions@master
        if: ${{ github.event.inputs.stage == 'release' }}
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.inputs.versionName }}
          versionStage: ' '

      - uses: EndBug/add-and-commit@v8
        with:
          add: app/build.gradle
          message: ${{steps.build_changelog.outputs.changelog}}
          default_author: github_actions
